adaptyvbio/ProteinFlow

- docs/index.html
- proteinflow/__init__.py
- proteinflow/utils/biotite_sse.py
- pyproject.toml
- tests/test_download.py
- add a `feature_functions` argument to `ProteinDataset`
- create `ProteinLoader` from a dataset by default
> make loader and dataset more flexible

- docs/index.html
- proteinflow/__init__.py
- proteinflow/scripts/proteinflow_cli.py
- pyproject.toml
- change default download tag
- fix a `node_features_type` bug
> Small fixes

- docs/index.html
- proteinflow/__init__.py
- pyproject.toml
- tests/test_download.py
- tests/test_generate.py
- add a warning for pair entry type
- add an intersection condition for pair entry type
- speed up processing by moving the length check to the beginning
> Speed up + intersection

- docs/index.html
- proteinflow/__init__.py
- pyproject.toml
- tests/test_download.py
- fix the bug with `classes_to_exclude` parameter
- add `sidechain_coords` feature
> Fix dataset + add sidechain coords

- .github/workflows/update-docs.yml
- .pre-commit-config.yaml
- bump_version.py
- proteinflow/__init__.py
- proteinflow/constants.py
- proteinflow/custom_mmcif.py
- proteinflow/pdb.py
- proteinflow/protein_loader.py
- proteinflow/sequences.py
- proteinflow/utils/biotite_sse.py
- proteinflow/utils/boto_utils.py
- proteinflow/utils/cluster_and_partition.py
- pyproject.toml
- setup.cfg
- tests/test_generate.py
- tests/test_sabdab.py
- add flake8, interrogate, pydocstyle pre-commit hooks
- fix some style errors
> Pre commit

- .pre-commit-config.yaml
- proteinflow/__init__.py
- proteinflow/protein_dataset.py
- proteinflow/protein_loader.py
- proteinflow/scripts/proteinflow_cli.py
- proteinflow/utils/boto_utils.py
- proteinflow/utils/cluster_and_partition.py
- tests/test_download.py
- tests/test_generate.py
- add random seed for splitting
- adjust split dictionaries for excluded files
- store class info in a single file
> Improve splitting

- .conda/arm64/meta.yaml
- .conda/default/meta.yaml
- README.md
- proteinflow/__init__.py
- proteinflow/utils/cluster_and_partition.py
- pyproject.toml
- improve behavior when the SAbDab server is throwing HTTP errors
- save temporary files in OS temporary folder
- print more information for SAbDab processing
- add SAbDab dataset to readme
> Improve SAbDab generation

- proteinflow/__init__.py
> Fix parameter display in logs

- README.md
- proteinflow/__init__.py
Add the `20230626_sabdab` tag to the README.
> Add a SAbDab dataset

- .pre-commit-config.yaml
- CONTRIBUTING.md
- commitlint.config.js
Add a pre-commit hook for commit messages.
> Add commitlint

- .github/workflows/python-publish.yml
- proteinflow/download/boto.py
- tests/test_download.py
Download datasets as archives to save time.
> Switch to archives

- proteinflow/data/__init__.py
Fix `get_sequence` with CDR parameter set.
> Fix a bug in ProteinEntry

- .conda/arm64/meta.yaml
- .conda/default/meta.yaml
- proteinflow/data/torch.py
- pyproject.toml
- fix some bugs in patching,
- expand patching to non-SabDab datasets,
- add `get_anchor_ind` method
> Improve patching

- proteinflow/data/torch.py
> Fix a masking bug

- proteinflow/data/torch.py
fix a rare issue with `force_binding_sites_frac > 0`
> Fix more masking bugs

- proteinflow/data/torch.py
add `cut_edges` dataset option to `ProteinLoader` constructor
> Fix ProteinLoader options

- .gitignore
- proteinflow/__init__.py
- proteinflow/download/boto.py
- proteinflow/split/__init__.py
- Deal with existing excluded.pickle,
- Remove the .zip file when downloading a dataset,
- Refactor some splitting code.
> Improve basic functions

- proteinflow/data/torch.py
resolve #123 
Make the error message clearer + attempt to find the classes dictionary when it is missing
> Improve classes handling

- proteinflow/split/__init__.py
Fix sorting files into folders with `--exclude_clusters`.
> Fix splitting

- proteinflow/data/torch.py
Add the option to set multiple CDRs in `ProteinDataset`.
> Select CDRs
